// flow-typed signature: af54f52564dad4a964af1926e9c3f9e5
// flow-typed version: <<STUB>>/gatsby_v2.24.7/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby/cache-dir/__tests__/dev-loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/error-overlay-handler' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/find-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/minimal-config' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/__tests__/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-browser-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-browser' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-runner-ssr' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/api-ssr-docs' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-runner-browser-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-runner-browser' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-runner-ssr' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/api-ssr-docs' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/create-react-context' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/default-html' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/dev-loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/develop-static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/emitter' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/ensure-resources' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/error-overlay-handler' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/find-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/gatsby-browser-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/navigation' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/normalize-page-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/polyfill-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/polyfills/fetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/polyfills/no-op' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/polyfills/object-assign' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/polyfills/whatwg-fetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/prefetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/production-app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/public-page-renderer-dev' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/public-page-renderer-prod' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/public-page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/query-result-store' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/react-lifecycles-compat' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/register-service-worker' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/root' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/route-announcer-props' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/socketIo' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/commonjs/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/create-react-context' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/default-html' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/dev-loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/develop-static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/emitter' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/ensure-resources' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/error-overlay-handler' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/find-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/gatsby-browser-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/loader' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/navigation' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/normalize-page-path' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/polyfill-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/polyfills/fetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/polyfills/no-op' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/polyfills/object-assign' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/polyfills/whatwg-fetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/prefetch' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/production-app' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/public-page-renderer-dev' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/public-page-renderer-prod' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/public-page-renderer' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/query-result-store' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/react-lifecycles-compat' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/register-service-worker' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/root' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/route-announcer-props' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/socketIo' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/cache-dir/strip-prefix' {
  declare module.exports: any;
}

declare module 'gatsby/cli' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bin/gatsby' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/__mocks__/require/exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/__mocks__/require/module-error' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/__mocks__/require/unusual-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/__mocks__/resolve-module-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/create-graphql-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/get-config-file' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/load' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-plugins/validate' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/load-themes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/log-line-function' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/page-hot-reloader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/prefer-default' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/redirects-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/remove-stale-jobs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/requires-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/resolve-module-exports' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bootstrap/schema-hot-reloader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-javascript' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/build' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/clean' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop-process' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop-static' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/develop' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/feedback' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/repl' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/serve' {
  declare module.exports: any;
}

declare module 'gatsby/dist/commands/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/common/query' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/db/sanitize-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/internal-data-bridge' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/load-babel-config/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/load-babel-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/prod-404/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/prod-404' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/create-page' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing' {
  declare module.exports: any;
}

declare module 'gatsby/dist/joi-schemas/joi' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/better-queue-custom-store' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/error-parser' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/file-parser' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/graphql-errors' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/graphql-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/graphql-span-tracer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/query-compiler' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/query-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/query-watcher' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/queue' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/redirects-writer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/query/utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions/add-page-dependency' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions/internal' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions/public' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/actions/restricted' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/machines/page-component' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/persist' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/plugin-runner' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/babelrc' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/component-data-dependencies' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/components' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/flattened-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/inference-metadata' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/jobs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/jobsv2' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/last-action' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes-by-type' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes-touched' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/page-data-stats' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/page-data' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/pages' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/pending-page-data-writes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/program' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/redirects' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/resolved-nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/schema-customization' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/static-queries-by-template' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/static-query-components' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/status' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/themes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/webpack-compilation-hash' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/reducers/webpack' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/run-fast-filters' {
  declare module.exports: any;
}

declare module 'gatsby/dist/redux/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/context' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/extensions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer/add-inferred-fields' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer/build-example-data' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer/inference-metadata' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer/is-file' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/infer/type-conflict-reporter' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/node-model' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/print' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/resolvers' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/schema-composer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/type-definitions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/built-in-types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/date' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/derived-types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/filter' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/node-interface' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/pagination' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/sort' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/type-builders' {
  declare module.exports: any;
}

declare module 'gatsby/dist/schema/types/type-defs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/build-schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/calculate-dirty-queries' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/create-pages-statefully' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/create-pages' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/customize-schema' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/extract-queries' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/initialize' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/post-bootstrap' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/rebuild-schema-with-site-pages' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/run-page-queries' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/run-static-queries' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/source-nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/start-webpack-server' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/write-out-redirects' {
  declare module.exports: any;
}

declare module 'gatsby/dist/services/write-out-requires' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/data-layer/actions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/data-layer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/data-layer/services' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/data-layer/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/query-running/actions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/query-running' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/query-running/services' {
  declare module.exports: any;
}

declare module 'gatsby/dist/state-machines/query-running/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-browser-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-node-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-node-helpers-docs' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-runner-error-parser' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/api-runner-node' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/app-data' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/assert-store' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-loader-helpers' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-loader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-parse-to-ast' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/browserslist' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/cache' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/create-node-id' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/create-schema-customization' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/detect-port-in-use-and-prompt' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/develop-proxy' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/did-you-mean' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/eslint-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/feedback' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/gatsby-dependents' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/gatsby-webpack-stats-extractor' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/gatsby-webpack-virtual-modules' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-cache' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-latest-apis' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-public-path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-ssl-cert' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-static-dir' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/get-value-at' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/is-32-bit-integer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/jobs-manager' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/js-chunk-names' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/local-eslint-config-finder' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/map-templates-to-static-query-hashes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/merge-gatsby-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/mett' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/normalize-page-path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/page-data' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/page-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/path' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/prepare-regex' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/prepare-urls' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/print-deprecation-warnings' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/print-instructions' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/profile' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/reach-router-add-basecontext-export-loader' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/restarting-screen' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/source-nodes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/stack-trace-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/start-server' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/test-require-error' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/tracer' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/tracer/jaeger-local' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/tracer/zipkin-local' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/tracer/zipkin-types.d' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/validate-page-component' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/wait-until-jobs-complete' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-error-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-hmr-hooks-patch' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-plugins' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-status' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack-utils' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack.config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack/corejs-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/websocket-manager' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/worker/child' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/worker/pool' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/worker/render-html' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/69bd6bf3-6f05fe53ad1680c7e154' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/app-384836ddf0313ee1b585' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/app-9f69a6123533b4be587d' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/app-fa2872c4213e78082067' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/component---src-pages-index-tsx-c881ec1a2ac12afe548a' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/framework-ce2f6724af2aeee4ac4a' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/polyfill-760942fb308ec169504e' {
  declare module.exports: any;
}

declare module 'gatsby/gatsby-admin-public/webpack-runtime-ff7171406f2f97b28062' {
  declare module.exports: any;
}

declare module 'gatsby/graphql' {
  declare module.exports: any;
}

declare module 'gatsby/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'gatsby/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby/cache-dir/__tests__/dev-loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/dev-loader'>;
}
declare module 'gatsby/cache-dir/__tests__/error-overlay-handler.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/error-overlay-handler'>;
}
declare module 'gatsby/cache-dir/__tests__/find-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/find-path'>;
}
declare module 'gatsby/cache-dir/__tests__/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/loader'>;
}
declare module 'gatsby/cache-dir/__tests__/minimal-config.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/minimal-config'>;
}
declare module 'gatsby/cache-dir/__tests__/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/static-entry'>;
}
declare module 'gatsby/cache-dir/__tests__/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/__tests__/strip-prefix'>;
}
declare module 'gatsby/cache-dir/api-runner-browser-plugins.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-browser-plugins'>;
}
declare module 'gatsby/cache-dir/api-runner-browser.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-browser'>;
}
declare module 'gatsby/cache-dir/api-runner-ssr.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-runner-ssr'>;
}
declare module 'gatsby/cache-dir/api-ssr-docs.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/api-ssr-docs'>;
}
declare module 'gatsby/cache-dir/app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/app'>;
}
declare module 'gatsby/cache-dir/commonjs/api-runner-browser-plugins.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-runner-browser-plugins'>;
}
declare module 'gatsby/cache-dir/commonjs/api-runner-browser.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-runner-browser'>;
}
declare module 'gatsby/cache-dir/commonjs/api-runner-ssr.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-runner-ssr'>;
}
declare module 'gatsby/cache-dir/commonjs/api-ssr-docs.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/api-ssr-docs'>;
}
declare module 'gatsby/cache-dir/commonjs/app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/app'>;
}
declare module 'gatsby/cache-dir/commonjs/create-react-context.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/create-react-context'>;
}
declare module 'gatsby/cache-dir/commonjs/default-html.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/default-html'>;
}
declare module 'gatsby/cache-dir/commonjs/dev-loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/dev-loader'>;
}
declare module 'gatsby/cache-dir/commonjs/develop-static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/develop-static-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/emitter.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/emitter'>;
}
declare module 'gatsby/cache-dir/commonjs/ensure-resources.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/ensure-resources'>;
}
declare module 'gatsby/cache-dir/commonjs/error-overlay-handler.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/error-overlay-handler'>;
}
declare module 'gatsby/cache-dir/commonjs/find-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/find-path'>;
}
declare module 'gatsby/cache-dir/commonjs/gatsby-browser-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/gatsby-browser-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/loader'>;
}
declare module 'gatsby/cache-dir/commonjs/navigation.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/navigation'>;
}
declare module 'gatsby/cache-dir/commonjs/normalize-page-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/normalize-page-path'>;
}
declare module 'gatsby/cache-dir/commonjs/page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/page-renderer'>;
}
declare module 'gatsby/cache-dir/commonjs/polyfill-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/polyfill-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/polyfills/fetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/polyfills/fetch'>;
}
declare module 'gatsby/cache-dir/commonjs/polyfills/no-op.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/polyfills/no-op'>;
}
declare module 'gatsby/cache-dir/commonjs/polyfills/object-assign.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/polyfills/object-assign'>;
}
declare module 'gatsby/cache-dir/commonjs/polyfills/whatwg-fetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/polyfills/whatwg-fetch'>;
}
declare module 'gatsby/cache-dir/commonjs/prefetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/prefetch'>;
}
declare module 'gatsby/cache-dir/commonjs/production-app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/production-app'>;
}
declare module 'gatsby/cache-dir/commonjs/public-page-renderer-dev.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/public-page-renderer-dev'>;
}
declare module 'gatsby/cache-dir/commonjs/public-page-renderer-prod.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/public-page-renderer-prod'>;
}
declare module 'gatsby/cache-dir/commonjs/public-page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/public-page-renderer'>;
}
declare module 'gatsby/cache-dir/commonjs/query-result-store.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/query-result-store'>;
}
declare module 'gatsby/cache-dir/commonjs/react-lifecycles-compat.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/react-lifecycles-compat'>;
}
declare module 'gatsby/cache-dir/commonjs/register-service-worker.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/register-service-worker'>;
}
declare module 'gatsby/cache-dir/commonjs/root.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/root'>;
}
declare module 'gatsby/cache-dir/commonjs/route-announcer-props.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/route-announcer-props'>;
}
declare module 'gatsby/cache-dir/commonjs/socketIo.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/socketIo'>;
}
declare module 'gatsby/cache-dir/commonjs/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/static-entry'>;
}
declare module 'gatsby/cache-dir/commonjs/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/commonjs/strip-prefix'>;
}
declare module 'gatsby/cache-dir/create-react-context.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/create-react-context'>;
}
declare module 'gatsby/cache-dir/default-html.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/default-html'>;
}
declare module 'gatsby/cache-dir/dev-loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/dev-loader'>;
}
declare module 'gatsby/cache-dir/develop-static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/develop-static-entry'>;
}
declare module 'gatsby/cache-dir/emitter.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/emitter'>;
}
declare module 'gatsby/cache-dir/ensure-resources.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/ensure-resources'>;
}
declare module 'gatsby/cache-dir/error-overlay-handler.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/error-overlay-handler'>;
}
declare module 'gatsby/cache-dir/find-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/find-path'>;
}
declare module 'gatsby/cache-dir/gatsby-browser-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/gatsby-browser-entry'>;
}
declare module 'gatsby/cache-dir/loader.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/loader'>;
}
declare module 'gatsby/cache-dir/navigation.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/navigation'>;
}
declare module 'gatsby/cache-dir/normalize-page-path.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/normalize-page-path'>;
}
declare module 'gatsby/cache-dir/page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/page-renderer'>;
}
declare module 'gatsby/cache-dir/polyfill-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/polyfill-entry'>;
}
declare module 'gatsby/cache-dir/polyfills/fetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/polyfills/fetch'>;
}
declare module 'gatsby/cache-dir/polyfills/no-op.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/polyfills/no-op'>;
}
declare module 'gatsby/cache-dir/polyfills/object-assign.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/polyfills/object-assign'>;
}
declare module 'gatsby/cache-dir/polyfills/whatwg-fetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/polyfills/whatwg-fetch'>;
}
declare module 'gatsby/cache-dir/prefetch.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/prefetch'>;
}
declare module 'gatsby/cache-dir/production-app.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/production-app'>;
}
declare module 'gatsby/cache-dir/public-page-renderer-dev.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/public-page-renderer-dev'>;
}
declare module 'gatsby/cache-dir/public-page-renderer-prod.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/public-page-renderer-prod'>;
}
declare module 'gatsby/cache-dir/public-page-renderer.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/public-page-renderer'>;
}
declare module 'gatsby/cache-dir/query-result-store.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/query-result-store'>;
}
declare module 'gatsby/cache-dir/react-lifecycles-compat.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/react-lifecycles-compat'>;
}
declare module 'gatsby/cache-dir/register-service-worker.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/register-service-worker'>;
}
declare module 'gatsby/cache-dir/root.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/root'>;
}
declare module 'gatsby/cache-dir/route-announcer-props.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/route-announcer-props'>;
}
declare module 'gatsby/cache-dir/socketIo.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/socketIo'>;
}
declare module 'gatsby/cache-dir/static-entry.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/static-entry'>;
}
declare module 'gatsby/cache-dir/strip-prefix.js' {
  declare module.exports: $Exports<'gatsby/cache-dir/strip-prefix'>;
}
declare module 'gatsby/cli.js' {
  declare module.exports: $Exports<'gatsby/cli'>;
}
declare module 'gatsby/dist/bin/gatsby.js' {
  declare module.exports: $Exports<'gatsby/dist/bin/gatsby'>;
}
declare module 'gatsby/dist/bootstrap/__mocks__/require/exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/__mocks__/require/exports'>;
}
declare module 'gatsby/dist/bootstrap/__mocks__/require/module-error.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/__mocks__/require/module-error'>;
}
declare module 'gatsby/dist/bootstrap/__mocks__/require/unusual-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/__mocks__/require/unusual-exports'>;
}
declare module 'gatsby/dist/bootstrap/__mocks__/resolve-module-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/__mocks__/resolve-module-exports'>;
}
declare module 'gatsby/dist/bootstrap/create-graphql-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/create-graphql-runner'>;
}
declare module 'gatsby/dist/bootstrap/get-config-file.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/get-config-file'>;
}
declare module 'gatsby/dist/bootstrap/index' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap'>;
}
declare module 'gatsby/dist/bootstrap/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/index' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/load.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/load'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/types.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/types'>;
}
declare module 'gatsby/dist/bootstrap/load-plugins/validate.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-plugins/validate'>;
}
declare module 'gatsby/dist/bootstrap/load-themes/index' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-themes'>;
}
declare module 'gatsby/dist/bootstrap/load-themes/index.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/load-themes'>;
}
declare module 'gatsby/dist/bootstrap/log-line-function.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/log-line-function'>;
}
declare module 'gatsby/dist/bootstrap/page-hot-reloader.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/page-hot-reloader'>;
}
declare module 'gatsby/dist/bootstrap/prefer-default.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/prefer-default'>;
}
declare module 'gatsby/dist/bootstrap/redirects-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/redirects-writer'>;
}
declare module 'gatsby/dist/bootstrap/remove-stale-jobs.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/remove-stale-jobs'>;
}
declare module 'gatsby/dist/bootstrap/requires-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/requires-writer'>;
}
declare module 'gatsby/dist/bootstrap/resolve-module-exports.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/resolve-module-exports'>;
}
declare module 'gatsby/dist/bootstrap/schema-hot-reloader.js' {
  declare module.exports: $Exports<'gatsby/dist/bootstrap/schema-hot-reloader'>;
}
declare module 'gatsby/dist/commands/build-html.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-html'>;
}
declare module 'gatsby/dist/commands/build-javascript.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-javascript'>;
}
declare module 'gatsby/dist/commands/build-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build-utils'>;
}
declare module 'gatsby/dist/commands/build.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/build'>;
}
declare module 'gatsby/dist/commands/clean.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/clean'>;
}
declare module 'gatsby/dist/commands/develop-process.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop-process'>;
}
declare module 'gatsby/dist/commands/develop-static.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop-static'>;
}
declare module 'gatsby/dist/commands/develop.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/develop'>;
}
declare module 'gatsby/dist/commands/feedback.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/feedback'>;
}
declare module 'gatsby/dist/commands/repl.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/repl'>;
}
declare module 'gatsby/dist/commands/serve.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/serve'>;
}
declare module 'gatsby/dist/commands/types.js' {
  declare module.exports: $Exports<'gatsby/dist/commands/types'>;
}
declare module 'gatsby/dist/db/common/query.js' {
  declare module.exports: $Exports<'gatsby/dist/db/common/query'>;
}
declare module 'gatsby/dist/db/index' {
  declare module.exports: $Exports<'gatsby/dist/db'>;
}
declare module 'gatsby/dist/db/index.js' {
  declare module.exports: $Exports<'gatsby/dist/db'>;
}
declare module 'gatsby/dist/db/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/db/nodes'>;
}
declare module 'gatsby/dist/db/sanitize-node.js' {
  declare module.exports: $Exports<'gatsby/dist/db/sanitize-node'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/index' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page'>;
}
declare module 'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/dev-404-page/raw_dev-404-page'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/index' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge'>;
}
declare module 'gatsby/dist/internal-plugins/internal-data-bridge/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/internal-data-bridge'>;
}
declare module 'gatsby/dist/internal-plugins/load-babel-config/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/load-babel-config/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/load-babel-config/index' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/load-babel-config'>;
}
declare module 'gatsby/dist/internal-plugins/load-babel-config/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/load-babel-config'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/index' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404'>;
}
declare module 'gatsby/dist/internal-plugins/prod-404/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/prod-404'>;
}
declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/create-page.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/create-page'>;
}
declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/gatsby-node'>;
}
declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/webpack-theme-component-shadowing'>;
}
declare module 'gatsby/dist/internal-plugins/webpack-theme-component-shadowing/index.js' {
  declare module.exports: $Exports<'gatsby/dist/internal-plugins/webpack-theme-component-shadowing'>;
}
declare module 'gatsby/dist/joi-schemas/joi.js' {
  declare module.exports: $Exports<'gatsby/dist/joi-schemas/joi'>;
}
declare module 'gatsby/dist/query/better-queue-custom-store.js' {
  declare module.exports: $Exports<'gatsby/dist/query/better-queue-custom-store'>;
}
declare module 'gatsby/dist/query/error-parser.js' {
  declare module.exports: $Exports<'gatsby/dist/query/error-parser'>;
}
declare module 'gatsby/dist/query/file-parser.js' {
  declare module.exports: $Exports<'gatsby/dist/query/file-parser'>;
}
declare module 'gatsby/dist/query/graphql-errors.js' {
  declare module.exports: $Exports<'gatsby/dist/query/graphql-errors'>;
}
declare module 'gatsby/dist/query/graphql-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/query/graphql-runner'>;
}
declare module 'gatsby/dist/query/graphql-span-tracer.js' {
  declare module.exports: $Exports<'gatsby/dist/query/graphql-span-tracer'>;
}
declare module 'gatsby/dist/query/index' {
  declare module.exports: $Exports<'gatsby/dist/query'>;
}
declare module 'gatsby/dist/query/index.js' {
  declare module.exports: $Exports<'gatsby/dist/query'>;
}
declare module 'gatsby/dist/query/query-compiler.js' {
  declare module.exports: $Exports<'gatsby/dist/query/query-compiler'>;
}
declare module 'gatsby/dist/query/query-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/query/query-runner'>;
}
declare module 'gatsby/dist/query/query-watcher.js' {
  declare module.exports: $Exports<'gatsby/dist/query/query-watcher'>;
}
declare module 'gatsby/dist/query/queue.js' {
  declare module.exports: $Exports<'gatsby/dist/query/queue'>;
}
declare module 'gatsby/dist/query/redirects-writer.js' {
  declare module.exports: $Exports<'gatsby/dist/query/redirects-writer'>;
}
declare module 'gatsby/dist/query/types.js' {
  declare module.exports: $Exports<'gatsby/dist/query/types'>;
}
declare module 'gatsby/dist/query/utils.js' {
  declare module.exports: $Exports<'gatsby/dist/query/utils'>;
}
declare module 'gatsby/dist/redux/actions/add-page-dependency.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions/add-page-dependency'>;
}
declare module 'gatsby/dist/redux/actions/index' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions'>;
}
declare module 'gatsby/dist/redux/actions/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions'>;
}
declare module 'gatsby/dist/redux/actions/internal.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions/internal'>;
}
declare module 'gatsby/dist/redux/actions/public.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions/public'>;
}
declare module 'gatsby/dist/redux/actions/restricted.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/actions/restricted'>;
}
declare module 'gatsby/dist/redux/index' {
  declare module.exports: $Exports<'gatsby/dist/redux'>;
}
declare module 'gatsby/dist/redux/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux'>;
}
declare module 'gatsby/dist/redux/machines/page-component.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/machines/page-component'>;
}
declare module 'gatsby/dist/redux/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/nodes'>;
}
declare module 'gatsby/dist/redux/persist.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/persist'>;
}
declare module 'gatsby/dist/redux/plugin-runner.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/plugin-runner'>;
}
declare module 'gatsby/dist/redux/reducers/babelrc.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/babelrc'>;
}
declare module 'gatsby/dist/redux/reducers/component-data-dependencies.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/component-data-dependencies'>;
}
declare module 'gatsby/dist/redux/reducers/components.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/components'>;
}
declare module 'gatsby/dist/redux/reducers/config.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/config'>;
}
declare module 'gatsby/dist/redux/reducers/flattened-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/flattened-plugins'>;
}
declare module 'gatsby/dist/redux/reducers/index' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers'>;
}
declare module 'gatsby/dist/redux/reducers/index.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers'>;
}
declare module 'gatsby/dist/redux/reducers/inference-metadata.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/inference-metadata'>;
}
declare module 'gatsby/dist/redux/reducers/jobs.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/jobs'>;
}
declare module 'gatsby/dist/redux/reducers/jobsv2.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/jobsv2'>;
}
declare module 'gatsby/dist/redux/reducers/last-action.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/last-action'>;
}
declare module 'gatsby/dist/redux/reducers/nodes-by-type.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes-by-type'>;
}
declare module 'gatsby/dist/redux/reducers/nodes-touched.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes-touched'>;
}
declare module 'gatsby/dist/redux/reducers/nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/nodes'>;
}
declare module 'gatsby/dist/redux/reducers/page-data-stats.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/page-data-stats'>;
}
declare module 'gatsby/dist/redux/reducers/page-data.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/page-data'>;
}
declare module 'gatsby/dist/redux/reducers/pages.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/pages'>;
}
declare module 'gatsby/dist/redux/reducers/pending-page-data-writes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/pending-page-data-writes'>;
}
declare module 'gatsby/dist/redux/reducers/program.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/program'>;
}
declare module 'gatsby/dist/redux/reducers/redirects.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/redirects'>;
}
declare module 'gatsby/dist/redux/reducers/resolved-nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/resolved-nodes'>;
}
declare module 'gatsby/dist/redux/reducers/schema-customization.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/schema-customization'>;
}
declare module 'gatsby/dist/redux/reducers/schema.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/schema'>;
}
declare module 'gatsby/dist/redux/reducers/static-queries-by-template.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/static-queries-by-template'>;
}
declare module 'gatsby/dist/redux/reducers/static-query-components.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/static-query-components'>;
}
declare module 'gatsby/dist/redux/reducers/status.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/status'>;
}
declare module 'gatsby/dist/redux/reducers/themes.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/themes'>;
}
declare module 'gatsby/dist/redux/reducers/webpack-compilation-hash.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/webpack-compilation-hash'>;
}
declare module 'gatsby/dist/redux/reducers/webpack.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/reducers/webpack'>;
}
declare module 'gatsby/dist/redux/run-fast-filters.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/run-fast-filters'>;
}
declare module 'gatsby/dist/redux/types.js' {
  declare module.exports: $Exports<'gatsby/dist/redux/types'>;
}
declare module 'gatsby/dist/schema/context.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/context'>;
}
declare module 'gatsby/dist/schema/extensions/index' {
  declare module.exports: $Exports<'gatsby/dist/schema/extensions'>;
}
declare module 'gatsby/dist/schema/extensions/index.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/extensions'>;
}
declare module 'gatsby/dist/schema/index' {
  declare module.exports: $Exports<'gatsby/dist/schema'>;
}
declare module 'gatsby/dist/schema/index.js' {
  declare module.exports: $Exports<'gatsby/dist/schema'>;
}
declare module 'gatsby/dist/schema/infer/add-inferred-fields.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer/add-inferred-fields'>;
}
declare module 'gatsby/dist/schema/infer/build-example-data.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer/build-example-data'>;
}
declare module 'gatsby/dist/schema/infer/index' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer'>;
}
declare module 'gatsby/dist/schema/infer/index.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer'>;
}
declare module 'gatsby/dist/schema/infer/inference-metadata.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer/inference-metadata'>;
}
declare module 'gatsby/dist/schema/infer/is-file.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer/is-file'>;
}
declare module 'gatsby/dist/schema/infer/type-conflict-reporter.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/infer/type-conflict-reporter'>;
}
declare module 'gatsby/dist/schema/node-model.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/node-model'>;
}
declare module 'gatsby/dist/schema/print.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/print'>;
}
declare module 'gatsby/dist/schema/resolvers.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/resolvers'>;
}
declare module 'gatsby/dist/schema/schema-composer.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/schema-composer'>;
}
declare module 'gatsby/dist/schema/schema.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/schema'>;
}
declare module 'gatsby/dist/schema/type-definitions.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/type-definitions'>;
}
declare module 'gatsby/dist/schema/types/built-in-types.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/built-in-types'>;
}
declare module 'gatsby/dist/schema/types/date.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/date'>;
}
declare module 'gatsby/dist/schema/types/derived-types.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/derived-types'>;
}
declare module 'gatsby/dist/schema/types/filter.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/filter'>;
}
declare module 'gatsby/dist/schema/types/node-interface.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/node-interface'>;
}
declare module 'gatsby/dist/schema/types/pagination.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/pagination'>;
}
declare module 'gatsby/dist/schema/types/sort.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/sort'>;
}
declare module 'gatsby/dist/schema/types/type-builders.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/type-builders'>;
}
declare module 'gatsby/dist/schema/types/type-defs.js' {
  declare module.exports: $Exports<'gatsby/dist/schema/types/type-defs'>;
}
declare module 'gatsby/dist/services/build-schema.js' {
  declare module.exports: $Exports<'gatsby/dist/services/build-schema'>;
}
declare module 'gatsby/dist/services/calculate-dirty-queries.js' {
  declare module.exports: $Exports<'gatsby/dist/services/calculate-dirty-queries'>;
}
declare module 'gatsby/dist/services/create-pages-statefully.js' {
  declare module.exports: $Exports<'gatsby/dist/services/create-pages-statefully'>;
}
declare module 'gatsby/dist/services/create-pages.js' {
  declare module.exports: $Exports<'gatsby/dist/services/create-pages'>;
}
declare module 'gatsby/dist/services/customize-schema.js' {
  declare module.exports: $Exports<'gatsby/dist/services/customize-schema'>;
}
declare module 'gatsby/dist/services/extract-queries.js' {
  declare module.exports: $Exports<'gatsby/dist/services/extract-queries'>;
}
declare module 'gatsby/dist/services/index' {
  declare module.exports: $Exports<'gatsby/dist/services'>;
}
declare module 'gatsby/dist/services/index.js' {
  declare module.exports: $Exports<'gatsby/dist/services'>;
}
declare module 'gatsby/dist/services/initialize.js' {
  declare module.exports: $Exports<'gatsby/dist/services/initialize'>;
}
declare module 'gatsby/dist/services/post-bootstrap.js' {
  declare module.exports: $Exports<'gatsby/dist/services/post-bootstrap'>;
}
declare module 'gatsby/dist/services/rebuild-schema-with-site-pages.js' {
  declare module.exports: $Exports<'gatsby/dist/services/rebuild-schema-with-site-pages'>;
}
declare module 'gatsby/dist/services/run-page-queries.js' {
  declare module.exports: $Exports<'gatsby/dist/services/run-page-queries'>;
}
declare module 'gatsby/dist/services/run-static-queries.js' {
  declare module.exports: $Exports<'gatsby/dist/services/run-static-queries'>;
}
declare module 'gatsby/dist/services/source-nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/services/source-nodes'>;
}
declare module 'gatsby/dist/services/start-webpack-server.js' {
  declare module.exports: $Exports<'gatsby/dist/services/start-webpack-server'>;
}
declare module 'gatsby/dist/services/types.js' {
  declare module.exports: $Exports<'gatsby/dist/services/types'>;
}
declare module 'gatsby/dist/services/write-out-redirects.js' {
  declare module.exports: $Exports<'gatsby/dist/services/write-out-redirects'>;
}
declare module 'gatsby/dist/services/write-out-requires.js' {
  declare module.exports: $Exports<'gatsby/dist/services/write-out-requires'>;
}
declare module 'gatsby/dist/state-machines/data-layer/actions.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/data-layer/actions'>;
}
declare module 'gatsby/dist/state-machines/data-layer/index' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/data-layer'>;
}
declare module 'gatsby/dist/state-machines/data-layer/index.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/data-layer'>;
}
declare module 'gatsby/dist/state-machines/data-layer/services.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/data-layer/services'>;
}
declare module 'gatsby/dist/state-machines/data-layer/types.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/data-layer/types'>;
}
declare module 'gatsby/dist/state-machines/query-running/actions.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/query-running/actions'>;
}
declare module 'gatsby/dist/state-machines/query-running/index' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/query-running'>;
}
declare module 'gatsby/dist/state-machines/query-running/index.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/query-running'>;
}
declare module 'gatsby/dist/state-machines/query-running/services.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/query-running/services'>;
}
declare module 'gatsby/dist/state-machines/query-running/types.js' {
  declare module.exports: $Exports<'gatsby/dist/state-machines/query-running/types'>;
}
declare module 'gatsby/dist/types.js' {
  declare module.exports: $Exports<'gatsby/dist/types'>;
}
declare module 'gatsby/dist/utils/api-browser-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-browser-docs'>;
}
declare module 'gatsby/dist/utils/api-node-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-node-docs'>;
}
declare module 'gatsby/dist/utils/api-node-helpers-docs.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-node-helpers-docs'>;
}
declare module 'gatsby/dist/utils/api-runner-error-parser.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-runner-error-parser'>;
}
declare module 'gatsby/dist/utils/api-runner-node.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/api-runner-node'>;
}
declare module 'gatsby/dist/utils/app-data.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/app-data'>;
}
declare module 'gatsby/dist/utils/assert-store.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/assert-store'>;
}
declare module 'gatsby/dist/utils/babel-loader-helpers.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-loader-helpers'>;
}
declare module 'gatsby/dist/utils/babel-loader.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-loader'>;
}
declare module 'gatsby/dist/utils/babel-parse-to-ast.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-parse-to-ast'>;
}
declare module 'gatsby/dist/utils/browserslist.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/browserslist'>;
}
declare module 'gatsby/dist/utils/cache.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/cache'>;
}
declare module 'gatsby/dist/utils/create-node-id.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/create-node-id'>;
}
declare module 'gatsby/dist/utils/create-schema-customization.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/create-schema-customization'>;
}
declare module 'gatsby/dist/utils/detect-port-in-use-and-prompt.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/detect-port-in-use-and-prompt'>;
}
declare module 'gatsby/dist/utils/develop-proxy.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/develop-proxy'>;
}
declare module 'gatsby/dist/utils/did-you-mean.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/did-you-mean'>;
}
declare module 'gatsby/dist/utils/eslint-config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/eslint-config'>;
}
declare module 'gatsby/dist/utils/feedback.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/feedback'>;
}
declare module 'gatsby/dist/utils/gatsby-dependents.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/gatsby-dependents'>;
}
declare module 'gatsby/dist/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/gatsby-webpack-eslint-graphql-schema-reload-plugin'>;
}
declare module 'gatsby/dist/utils/gatsby-webpack-stats-extractor.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/gatsby-webpack-stats-extractor'>;
}
declare module 'gatsby/dist/utils/gatsby-webpack-virtual-modules.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/gatsby-webpack-virtual-modules'>;
}
declare module 'gatsby/dist/utils/get-cache.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-cache'>;
}
declare module 'gatsby/dist/utils/get-latest-apis.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-latest-apis'>;
}
declare module 'gatsby/dist/utils/get-public-path.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-public-path'>;
}
declare module 'gatsby/dist/utils/get-ssl-cert.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-ssl-cert'>;
}
declare module 'gatsby/dist/utils/get-static-dir.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-static-dir'>;
}
declare module 'gatsby/dist/utils/get-value-at.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/get-value-at'>;
}
declare module 'gatsby/dist/utils/is-32-bit-integer.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/is-32-bit-integer'>;
}
declare module 'gatsby/dist/utils/jobs-manager.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/jobs-manager'>;
}
declare module 'gatsby/dist/utils/js-chunk-names.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/js-chunk-names'>;
}
declare module 'gatsby/dist/utils/local-eslint-config-finder.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/local-eslint-config-finder'>;
}
declare module 'gatsby/dist/utils/map-templates-to-static-query-hashes.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/map-templates-to-static-query-hashes'>;
}
declare module 'gatsby/dist/utils/merge-gatsby-config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/merge-gatsby-config'>;
}
declare module 'gatsby/dist/utils/mett.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/mett'>;
}
declare module 'gatsby/dist/utils/normalize-page-path.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/normalize-page-path'>;
}
declare module 'gatsby/dist/utils/page-data.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/page-data'>;
}
declare module 'gatsby/dist/utils/page-html.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/page-html'>;
}
declare module 'gatsby/dist/utils/path.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/path'>;
}
declare module 'gatsby/dist/utils/prepare-regex.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/prepare-regex'>;
}
declare module 'gatsby/dist/utils/prepare-urls.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/prepare-urls'>;
}
declare module 'gatsby/dist/utils/print-deprecation-warnings.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/print-deprecation-warnings'>;
}
declare module 'gatsby/dist/utils/print-instructions.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/print-instructions'>;
}
declare module 'gatsby/dist/utils/profile.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/profile'>;
}
declare module 'gatsby/dist/utils/reach-router-add-basecontext-export-loader.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/reach-router-add-basecontext-export-loader'>;
}
declare module 'gatsby/dist/utils/restarting-screen.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/restarting-screen'>;
}
declare module 'gatsby/dist/utils/source-nodes.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/source-nodes'>;
}
declare module 'gatsby/dist/utils/stack-trace-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/stack-trace-utils'>;
}
declare module 'gatsby/dist/utils/start-server.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/start-server'>;
}
declare module 'gatsby/dist/utils/test-require-error.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/test-require-error'>;
}
declare module 'gatsby/dist/utils/tracer/index' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer'>;
}
declare module 'gatsby/dist/utils/tracer/index.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer'>;
}
declare module 'gatsby/dist/utils/tracer/jaeger-local.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer/jaeger-local'>;
}
declare module 'gatsby/dist/utils/tracer/zipkin-local.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer/zipkin-local'>;
}
declare module 'gatsby/dist/utils/tracer/zipkin-types.d.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/tracer/zipkin-types.d'>;
}
declare module 'gatsby/dist/utils/validate-page-component.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/validate-page-component'>;
}
declare module 'gatsby/dist/utils/wait-until-jobs-complete.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/wait-until-jobs-complete'>;
}
declare module 'gatsby/dist/utils/webpack-error-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-error-utils'>;
}
declare module 'gatsby/dist/utils/webpack-hmr-hooks-patch.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-hmr-hooks-patch'>;
}
declare module 'gatsby/dist/utils/webpack-plugins.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-plugins'>;
}
declare module 'gatsby/dist/utils/webpack-status.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-status'>;
}
declare module 'gatsby/dist/utils/webpack-utils.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack-utils'>;
}
declare module 'gatsby/dist/utils/webpack.config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack.config'>;
}
declare module 'gatsby/dist/utils/webpack/corejs-resolver.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack/corejs-resolver'>;
}
declare module 'gatsby/dist/utils/websocket-manager.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/websocket-manager'>;
}
declare module 'gatsby/dist/utils/worker/child.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/worker/child'>;
}
declare module 'gatsby/dist/utils/worker/pool.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/worker/pool'>;
}
declare module 'gatsby/dist/utils/worker/render-html.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/worker/render-html'>;
}
declare module 'gatsby/gatsby-admin-public/69bd6bf3-6f05fe53ad1680c7e154.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/69bd6bf3-6f05fe53ad1680c7e154'>;
}
declare module 'gatsby/gatsby-admin-public/app-384836ddf0313ee1b585.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/app-384836ddf0313ee1b585'>;
}
declare module 'gatsby/gatsby-admin-public/app-9f69a6123533b4be587d.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/app-9f69a6123533b4be587d'>;
}
declare module 'gatsby/gatsby-admin-public/app-fa2872c4213e78082067.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/app-fa2872c4213e78082067'>;
}
declare module 'gatsby/gatsby-admin-public/component---src-pages-index-tsx-c881ec1a2ac12afe548a.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/component---src-pages-index-tsx-c881ec1a2ac12afe548a'>;
}
declare module 'gatsby/gatsby-admin-public/framework-ce2f6724af2aeee4ac4a.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/framework-ce2f6724af2aeee4ac4a'>;
}
declare module 'gatsby/gatsby-admin-public/polyfill-760942fb308ec169504e.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/polyfill-760942fb308ec169504e'>;
}
declare module 'gatsby/gatsby-admin-public/webpack-runtime-ff7171406f2f97b28062.js' {
  declare module.exports: $Exports<'gatsby/gatsby-admin-public/webpack-runtime-ff7171406f2f97b28062'>;
}
declare module 'gatsby/graphql.js' {
  declare module.exports: $Exports<'gatsby/graphql'>;
}
declare module 'gatsby/scripts/postinstall.js' {
  declare module.exports: $Exports<'gatsby/scripts/postinstall'>;
}
declare module 'gatsby/utils.js' {
  declare module.exports: $Exports<'gatsby/utils'>;
}
