// flow-typed signature: f7a01ad2bfbdcbd9940769b886f4bb48
// flow-typed version: <<STUB>>/netlify-cms-app_v2.12.18/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify-cms-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify-cms-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify-cms-app/dist/esm/extensions' {
  declare module.exports: any;
}

declare module 'netlify-cms-app/dist/esm' {
  declare module.exports: any;
}

declare module 'netlify-cms-app/dist/esm/locales' {
  declare module.exports: any;
}

declare module 'netlify-cms-app/dist/netlify-cms-app' {
  declare module.exports: any;
}

declare module 'netlify-cms-app/src/extensions' {
  declare module.exports: any;
}

declare module 'netlify-cms-app/src' {
  declare module.exports: any;
}

declare module 'netlify-cms-app/src/locales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify-cms-app/dist/esm/extensions.js' {
  declare module.exports: $Exports<'netlify-cms-app/dist/esm/extensions'>;
}
declare module 'netlify-cms-app/dist/esm/index' {
  declare module.exports: $Exports<'netlify-cms-app/dist/esm'>;
}
declare module 'netlify-cms-app/dist/esm/index.js' {
  declare module.exports: $Exports<'netlify-cms-app/dist/esm'>;
}
declare module 'netlify-cms-app/dist/esm/locales.js' {
  declare module.exports: $Exports<'netlify-cms-app/dist/esm/locales'>;
}
declare module 'netlify-cms-app/dist/netlify-cms-app.js' {
  declare module.exports: $Exports<'netlify-cms-app/dist/netlify-cms-app'>;
}
declare module 'netlify-cms-app/src/extensions.js' {
  declare module.exports: $Exports<'netlify-cms-app/src/extensions'>;
}
declare module 'netlify-cms-app/src/index' {
  declare module.exports: $Exports<'netlify-cms-app/src'>;
}
declare module 'netlify-cms-app/src/index.js' {
  declare module.exports: $Exports<'netlify-cms-app/src'>;
}
declare module 'netlify-cms-app/src/locales.js' {
  declare module.exports: $Exports<'netlify-cms-app/src/locales'>;
}
