// flow-typed signature: fe55856ebce3b66ab6c0a8a6de309111
// flow-typed version: <<STUB>>/react-disqus-comments_v1.4.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-disqus-comments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-disqus-comments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-disqus-comments/build/components/DisqusThread' {
  declare module.exports: any;
}

declare module 'react-disqus-comments/build/main' {
  declare module.exports: any;
}

declare module 'react-disqus-comments/dist/react-disqus-thread' {
  declare module.exports: any;
}

declare module 'react-disqus-comments/dist/react-disqus-thread.min' {
  declare module.exports: any;
}

declare module 'react-disqus-comments/lib/components/DisqusThread' {
  declare module.exports: any;
}

declare module 'react-disqus-comments/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-disqus-comments/build/components/DisqusThread.js' {
  declare module.exports: $Exports<'react-disqus-comments/build/components/DisqusThread'>;
}
declare module 'react-disqus-comments/build/main.js' {
  declare module.exports: $Exports<'react-disqus-comments/build/main'>;
}
declare module 'react-disqus-comments/dist/react-disqus-thread.js' {
  declare module.exports: $Exports<'react-disqus-comments/dist/react-disqus-thread'>;
}
declare module 'react-disqus-comments/dist/react-disqus-thread.min.js' {
  declare module.exports: $Exports<'react-disqus-comments/dist/react-disqus-thread.min'>;
}
declare module 'react-disqus-comments/lib/components/DisqusThread.js' {
  declare module.exports: $Exports<'react-disqus-comments/lib/components/DisqusThread'>;
}
declare module 'react-disqus-comments/lib/main.js' {
  declare module.exports: $Exports<'react-disqus-comments/lib/main'>;
}
